microsoft/typed-rest-client

lib/Handlers.ts
lib/handlers/basiccreds.ts
lib/handlers/bearertoken.ts
lib/handlers/ntlm.ts
lib/handlers/personalaccesstoken.ts
tsconfig.json

Usage: `import * as httphandlers from "typed-rest-client/Handlers"`

Added simple export for handlers

---

package.json

Downgrade node version dev dependency.

Downgrade node version dev dependency.

---

.vsts.ci.yml

Using this PR branch to test new build definitions then I will update the yaml file at the end.

Add YAML file

---

samples/common.ts
samples/http.ts

Added proxy sample

---

lib/handlers/ntlm.ts
samples/handlers.ts
samples/webSample/server.ts

Use const instead of var

---

lib/handlers/ntlm.ts
package-lock.json
package.json

Allowing workstation and domain to be undefined 

---

lib/RestClient.ts
package.json

Accept error message in body as a string

---

lib/HttpClient.ts
lib/Interfaces.ts
package-lock.json
package.json
test/units/httptests.ts

Allow users to whitelist presigned url patterns
Fixes #126

Add option for presigned urls

---

lib/HttpClient.ts
lib/Interfaces.ts
test/units/httptests.ts

Wasn't approved yet, accidentally merged

Revert "Enable retries on some 500 codes on reads"

---

package-lock.json
package.json

There are basically no significant breaking changes and 3.1.5 is stable. Enables some new features for future development.

Update typescript to 3.1.5

---

lib/HttpClient.ts
package-lock.json
package.json

Will add a sample later as well. Fixes #152

Enable web usage without webpack

---

lib/HttpClient.ts

Fix data corruption

---

lib/HttpClient.ts

Reverts microsoft/typed-rest-client#168

Revert "Fix data corruption" PR

---

lib/HttpClient.ts
test/tests/httptests.ts

See #167.
Also added a test to check the fix.

Fix data corruption - 2nd attempt

---

lib/HttpClient.ts
lib/Interfaces.ts
test/tests/httptests.ts
test/units/httptests.ts

Allowing redirect downgrade from HTTPS to HTTP should be optional

---

lib/HttpClient.ts

Missing TooManyRequests (429) http code

---

package-lock.json
package.json
test/package-lock.json

Bump version

---

lib/HttpClient.ts

Remove unused variable

---

lib/RestClient.ts

We already allow this in the Http Client, just getting the typing right in the restClient

UserAgent should allow null/undefined

---

lib/RestClient.ts

Makes RestClient._processResponse protected

---

lib/Util.ts
test/package-lock.json
test/units/httptests.ts

PR to fix Issue https://github.com/microsoft/typed-rest-client/issues/203

Adding and checking for supported encodings in util function to avoid exception

---

lib/HttpClient.ts
package-lock.json
package.json

It seems that timeout is not being passed to request info - fixed it and passed it to request info also.

Passed timeout to info.options

---

lib/HttpClient.ts
package-lock.json
package.json
test/package-lock.json
test/tests/httptests.ts

Fix infinite retry loop

---

package-lock.json
package.json
test/package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/typed-rest-client/258)

Updating Underscore to resolve SNYK-JS-UNDERSCORE-1080984

---

azure-pipelines.yml

Add pool to Publish_package job

---

azure-pipelines.yml
ci/create-release-notes.js
ci/utils.js
package-lock.json
package.json

The PR adds release notes automatization. 
The script calls when we build and publish the package from the master branch. Also the related tag and the description will be created

Add release notes automatization

---

package-lock.json
package.json
samples/basic/package-lock.json
samples/react/package-lock.json
samples/webSample/package-lock.json
samples/webpack/package-lock.json
test/package-lock.json

In this PR I bumped the qs package version to 6.10.3 to fix vulnerability issue
Please check https://nvd.nist.gov/vuln/detail/CVE-2022-24999

Bump the qs version to fix vulnerability issue

---

lib/HttpClient.ts
package-lock.json
package.json

[Related issue](https://github.com/microsoft/typed-rest-client/issues/372)

Add `EHOSTUNREACH` to `NetworkRetryErrors` list
