microsoft/typed-rest-client

lib/handlers/basiccreds.ts
lib/handlers/bearertoken.ts
lib/handlers/ntlm.ts
lib/handlers/personalaccesstoken.ts
tsconfig.json

Force consistent casing across code. This will allow people to use this library on linux builds, removing this compile error: 
```
src/client/HttpClient.ts(5,33): error TS2307: Cannot find module 'typed-rest-client/interfaces'.
```
Fixes #26

refactor(casing): Force consistent casing

---

lib/RestClient.ts
lib/Util.ts
package-lock.json
package.json
test/resttests.ts

This PR adds the option to include an option to preserve the pathname specified in the base URL for the Rest Client. Default is false (maintains old behavior)

Support path in the base url

---

make.js
package-lock.json
package.json
test/resttests.ts

- Requirement for node version
- Requirement for npm version
- Remove calls to build/clean from other methods. They need to be called on their own.
- Increase timeout for slow tests(run on my home machine)
#27

Enforce node and npm versions in make.js

---

make.js

We only want to enforce versions on build. When running the tests the node version changes also change the npm version.
I found this while starting to set up builds on VSTS. This is the setup so far (using UI instead of YAML to get it working first ):
After Use Node 4.8.6 runs and we start doing npm run test, we were getting this issue:
ERROR: requires npm >= 5.5.1.  installed: 2.15.11
I believe this change will resolve the issue since we are just testing and the versions won't be enforced.
I could also see an argument for adding a node only version enforced when testing.

Only enforce version on build.

---

lib/HttpClient.ts
lib/Interfaces.ts
lib/Util.ts
lib/handlers/basiccreds.ts
lib/handlers/bearertoken.ts
lib/handlers/ntlm.ts
lib/handlers/personalaccesstoken.ts
lib/opensource/node-http-ntlm/ntlm.js
package-lock.json
package.json
samples/handlers.ts
samples/package-lock.json
test/httptests.ts
test/package-lock.json
test/resttests.ts

NOTE: I combined all my changes into one commit to make things cleaner.
This change adds an authorization handler for NTLM.
Due to the way NTLM works on connections there is some refactoring to expose a raw request in the HttpClient that uses callbacks. The method that existed before, requestRaw, calls in to this. There were some bugs regarding hanging sockets so that is why there is code to readBody on the responses before making the next request.
#16

Add NTLM authorization handler.

---

README.md

Short change to document what versions of Node we support.
#41

Documentation.

---

lib/RestClient.ts
test/resttests.ts

This PR changes `RestClient._processResult()` to return a null result to match the behavior of the documentation. It previously returned `undefined`. It also updates the signaure of `RestResponse<T>` accordingly.

Return 'null' on status 404

---

lib/HttpClient.ts
test/httptests.ts

Implementation is missing 303 redirect support.
I am facing issue downloading a file from a resource which is using this redirect to point to the actual resource.

Handle 303 SeeOther redirect.

---

README.md
make.js
package-lock.json
package.json
test/httptests.ts
test/package-lock.json
test/resttests.ts
test/tests/httptests.ts
test/tests/resttests.ts
test/tests/tsconfig.json
test/units/httptests.ts
test/units/resttests.ts
test/units/tsconfig.json

Switched tests to use nock to spoof Http requests instead of connecting to httpBin. Eliminates timeout failures for tests and allows offline testing. Added tests to ensure that response bodies are included when error is thrown.
Fixes #72 and closes Microsoft/vsts-node-api#34

Updated tests to use Nock instead of httpBin

---

lib/RestClient.ts
test/units/resttests.ts

Builds off of @etiago's closed PR https://github.com/Microsoft/typed-rest-client/pull/69, makes it optional instead of mandatory to fix issues with back compat, and adds tests.
Fixes #68

Adding optional date reviver

---

README.md

The folder seems to have changed in https://github.com/Microsoft/typed-rest-client/commit/e268bebc23aa8ec92475a101448f5b634d42eb2f#diff-cd48b3466cac686a136aa1ca179b659b which means the links aren't working.

Update links to test files in readme

---

lib/RestClient.ts

In case user specifies a custom Content-Type header (necessary at example in case we are using uploadStream to upload a file via mutipart/formdata standard (RFC 2388) the default one will not be added.
The problem is that the check over Content-Type header is case sensitive, so if you added a content-type header, this will not be detected and used correctly.
This makes the comparison case sensitive.
Closes #96

Headers checking in headersFromOptions is now case sensitive

---

package.json
test/package-lock.json

#98
* is used only in tests
* will brings a lot transitive dependencies into production environment

moving nock from dependency to devDependencies

---

.gitignore
.vscode/settings.json
lib/Util.ts
package-lock.json
package.json
test/package-lock.json
test/tests/httptests.ts
test/units/httptests.ts

Reverts Microsoft/typed-rest-client#101
This introduced changes that break tests for lower versions of node. I'll add back the first commit manually

Revert "Fix getUrl for systems that don't support path.posix"

---

test/tests/httptests.ts

Querying http://httpbin.org/get now returns an obj.url of http**s**://httpbin.org/get for some reason. This should fix our [failing tests](https://dev.azure.com/ms/typed-rest-client/_build?definitionId=42) (I think)

Fix failing tests

---

lib/HttpClient.ts

Current implementation considers HTTP_PROXY and HTTPS_PROXY in _getProxy as fallback when request does not provide a proxy configuration but system has the variables configured.
unfortunately it ignores the NO_PROXY settings.
With this change the _httpProxyBypassHosts gets initiallized (as fallback) with NO_PROXY environment settings, and gets overwritten by requestOptions.proxy.proxyBypassHost if available.

Consider NO_PROXY environment variable for default proxyBypassHosts List

---

lib/Interfaces.ts
lib/RestClient.ts
lib/Util.ts
package-lock.json
package.json
test/tests/resttests.ts
test/units/resttests.ts

** Description **:
Per Issue #172 reported, this PR will allow sending query-parameters with RestClient GET Requests.
**Introduced Changes**:
- Introduced a new common interface IRequestQueryParams, which can be globally used by any contributors willing to benefit from it OR build upon it after this contribution.
```
interface IRequestQueryParams {
options?: {
separator?: string,
arrayFormat?: string,
shouldAllowDots?: boolean
shouldOnlyEncodeValues?: boolean,
},
params: {
[name: string]: string | number | (string | number)[]
}
}
```
- function **getUrl** of Util.ts to receive _optional_ query parameters object, to use while building the request's URL: `getUrl(resource: string, baseUrl?: string, queryParams?: IRequestQueryParams)`.
- Modified the `RestClient.ts` module so that the …

Support adding query-parameters in RestClient Requests.

---

lib/HttpClient.ts
test/package-lock.json
test/units/httptests.ts

- Use `socket.destroy()` to ensure no more I/O happens on socket( i.e. closed), in favour of `socket.end()` which currently causes a **TypeError**.
Ref. [socket.destroy([exception])](https://nodejs.org/api/net.html#net_socket_destroy_exception)
- This added logic will ensure a proper Error with a comprehensive message: _Request timeout: /path_ is returned as result of Socket timeouts.
- Added a  _nock_ unit-test to address issue.
- Fixes #159 
**Change**
_Current Behavior_: `Uncaught TypeError: socket.end is not a function`
_Added Behaviour_: `Error: Request timeout: /path` which is triggered by Promise rejection, due socket timeouts.

[fix]: fix TypeError on socket.end() and ensure proper error message on timeouts

---

lib/HttpClient.ts
test/package-lock.json
test/tests/httptests.ts

- This PR fixes a bug where the `readBody()` function which returns a **Promise** has two consecutive `resolve()` of which both gets called.
- An `if-else` block is added to resolve the Promise only **once**.

fix: Add if-else block before Resolving the Promise in HttpClient's readBody() function

---

lib/handlers/ntlm.ts

Deprecate ntlm

---

lib/handlers/basiccreds.ts
lib/handlers/bearertoken.ts
lib/handlers/personalaccesstoken.ts
test/units/handlers.ts

This PR fixes a security issue.
**Current behavior**
1. Send any request with `BasicCredentialHandler`, `BearerCredentialHandler` or `PersonalAccessTokenCredentialHandler`.
2. The target host may return a redirection (3xx), with a link to a second host.
3. The next request will use the credentials to authenticate with the second host, by setting the `Authorization` header.
**Expected behavior**
3. The next request will NOT set the `Authorization` header.
See the same issue for CURL: 
1. [HTTP authentication leak in redirects](https://curl.haxx.se/docs/CVE-2018-1000007.html) - I used the same solution as CURL did.
2. [CVE-2018-1000007](https://nvd.nist.gov/vuln/detail/CVE-2018-1000007).

Disable authentications on redirections

---

lib/RestClient.ts
test/package-lock.json
test/tests/resttests.ts

Thanks to @hamzahejja for #180 
I noticed that this was only supported for `GET` requests. It looks like the REST dissertation or HTTP spec don't really take a stance on query params in a `DELETE` requests so this does seem to be done in the wild (for example: https://developer.atlassian.com/cloud/jira/software/rest/#api-builds-0-1-bulkByProperties-delete).

Support adding query params for HTTP Delete

---

lib/HttpClient.ts
package-lock.json
package.json

This will add handling when we have a network failure.
Occurs when the ADO Connection itself goes down and not return any status code.
The following network errors will be retried `'ECONNRESET', 'ENOTFOUND', 'ESOCKETTIMEDOUT', 'ETIMEDOUT', 'ECONNREFUSED'`

Added handling for when we have network failures in the retry mechanism

---

lib/Constants.ts
lib/Util.ts
package-lock.json
package.json
test/package-lock.json
test/units/utiltests.ts

We need to revert this PR https://github.com/microsoft/typed-rest-client/pull/286 since it is contains changes that is not compatible with node 6

Revert Fix processing of proxybypass variables from environment #286

---

.github/workflows/all-tests.yaml
azure-pipelines.yml
make.js

Add node 6, 10 and 14 to GitHub Actions and Azure Pipeline tests, lower npm requirements in make.js due to it being unable to use node 6

Add node 6, 10 and 14 to GitHub Actions and Azure Pipeline tests

---

azure-pipelines.yml
test/tests/httptests.ts

Currently the pipeline is not working because the default image is assumed to be ubuntu-16, which is removed.
This PR changes the image to ubuntu-20
Also, this introduces a temporary fix for [node 6 / node 8 certificate issue](https://stackoverflow.com/questions/62128611/nodejs-certificate-has-expired) in unit tests.

Fix broken azure pipeline

---

lib/HttpClient.ts

Fixes #321
Currently there are no performance tests that I could find, not sure how you folks might want to go about doing that in order to have one "fail in the absence of [my] non-test code changes." Consequently I haven't modified the tests.

Reduce Buffer copies in HttpClient

---

package-lock.json
package.json

Fixed recent vulnerabilities:
- npm audit fix 
- bumped mocha dependency
Testing - tested locally with node-api library and substituted typed-rest-client - works fine with the simple build api scenarios.

Fixed recent vulnerabilities - npm audit fix, bumped mocha dependency

---

CONTRIBUTING.md
README.md

**Description**: This PR removes mention of node 4 support since it's already not supported for a long time.
Changelog:
- Removed note about node 4 from repo README
- Remove note about node 4 from contributing guide

Removed mention of node 4 support

---

azure-pipelines.yml
make.js
package-lock.json
test/tests/httptests.ts

- Fixed redirect tests
- Updated yml to run tests in parallel on different platforms and node js versions

Update azure devops pipeline and fix tests

---

azure-pipelines.yml

Add a stage to Publish typed-rest-client to npm automatically

Add publish stage to pipeline

---

azure-pipelines.yml

- add trigger
- add publishToNpm parameter
- fix condition

Add publishToNpm parameter

---

azure-pipelines.yml

- Remove useless lines
- New SC for npm
- Migrate the pipeline to another pool and org

1ES Migration

---

.npmrc
azure-pipelines.yml
package-lock.json
samples/basic/.npmrc
samples/basic/package-lock.json
samples/react/.npmrc
samples/react/package-lock.json
samples/webSample/.npmrc
samples/webSample/package-lock.json
samples/webpack/.npmrc
samples/webpack/package-lock.json
test/.npmrc
test/package-lock.json

**Description**: This PR adds **.npmrc** to all packages in the repository to consume packages from the internal feed.
**Related**: [AB#2197030](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2197030)

Migration to CFS

---

lib/HttpClient.ts
lib/Interfaces.ts
package-lock.json
package.json
samples/basic/package-lock.json
test/package-lock.json

**WI**
[AB#2212397](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2212397)
**Description**
Since Node 19 global http agent uses HTTP Keep-Alive and a 5 second timeout by default: https://nodejs.org/api/http.html#httpglobalagent. 
This might cause issues like this one with `UseDotNet` task: https://github.com/microsoft/azure-pipelines-tasks/issues/20396
I added `globalAgentOptions` property to `IRequestOptions` to be able to set `timeout` and `keepAlive` parameters for global agent as needed when using `HttpClient`.

Add ability to pass global agent options for `HttpClient`

---

samples/react/package-lock.json
samples/react/package.json

Fixes: https://github.com/microsoft/typed-rest-client/security/dependabot/259
The package `elliptic` is present in `package-lock.json` as a transitive dependency, pulled via the following tree:
```json
`-- vite-plugin-node-polyfills@0.22.0
`-- node-stdlib-browser@1.2.0
`-- crypto-browserify@3.12.0
+-- browserify-sign@4.2.3
| `-- elliptic@6.6.1
`-- create-ecdh@4.0.4
`-- elliptic@6.6.1 
```
Both upstream dependencies are compatible with newer versions of `elliptic`:
* **`browserify-sign`** supports `elliptic@^6.5.5`:
[https://github.com/browserify/browserify-sign/blob/main/package.json](https://github.com/browserify/browserify-sign/blob/main/package.json)
* **`create-ecdh`** supports `elliptic@^6.5.3`:
[https://github.com/browserify/createECDH/blob/master/package.json](https://github.com/bro …

Override elliptic version to 6.6.1
